### ISSUE TITLE
Hello, may I ask when it will be open source？

### ISSUE THREAD

**Issue by liweizhen111** [LiXuefeng2020ai/GZPL#1]

**Comment by LiXuefeng2020ai** [comment]
Sorry, I was busy with work a while ago and I didn't organize it well. Please forgive me for delaying your work ~
The code is now open source.
Due to the rush of sorting out, there may be some configuration issues, please feel free to communicate on github or email ~

**Comment by liweizhen111** [comment]
I get it, Thanks for your interesting work!
